---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft-jacob
  namespace: minecraft-jacob
  labels:
    app: minecraft
    clusterid: jacob  
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: minecraft
      clusterid: jacob
