---
apiVersion: v1
kind: Namespace
metadata:
  name: minecraft-jacob
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: minecraft-jacob
  labels:
    app: minecraft
    clusterid: jacob
spec:
  type: LoadBalancer
  ports:
  - name: minecraft
    port: 25565
    protocol: TCP
    targetPort: 25565
  selector:
    app: minecraft
    clusterid: jacob
